### PR TITLE
CFMT faces experiment

### PR DESCRIPTION
**Pull request by Stajduhar-A**

### CODE REVIEW

**Comment by steffejr** [comment]
Hello. I just ran through the experiment and tested it. Everything worked really well. Good job. I just have a couple of concerns. 

It was a little 'odd' to have some photos include hair in the photos. That and the fact that once the photos started having noise added to them there were photos of different formats and cropping. It may be part of the experiment, but it through me to have a lot of images in a rather standard format and some in a different format. Maybe that is part of the experiment though!

I find the background a bit dark, making not a lot of contrast between the text and background.

I do not know what the experiment is, but based on the results file it looks like a challenge to analyze. Can you add some more info such as correct/incorrect; image upside down/rightside up; face pointed right/left/center; amount of noise added.
I know you can probably extract that info from your stimulus name, but it would make your life a lot easier to incorporate it into the results during the experiment. 

I am a little concerned about the "people names" included in the image file names. Is that OK?

I wonder if the code could be written in a bit more of a robust fashion. Right now it looks like A LOT of work went into this code, with each image file hard-coded and you need to specify the dimensions of every image. Why are the images not standardized in size? Or can you make a structure (stored in a JS file) that contains the image paths and their dimensions? That way you cycle through the structure and read over image path and dimensions? This is instead of hard coding it all into the main HTML file?

**Comment by pjkohler** [comment]
Hi @steffejr

I agree with most of your concerns, especially with regards to the cumbersome nature of the code. I have communicated these concerns to @Stajduhar-A. The plan is still that she will try to address them, but if she is unable or unwilling to find the time, I will make the necessary changes. This should be resolved with the next month or so. 

Thanks!

/Peter

**Comment by steffejr** [comment]
I mean there is a balance that needs to be struck between awesome, reusable code and a working experiment. 

Also there is no setup file like we discussed to include instruction text and modifiable parameters.

**Comment by pjkohler** [comment]
I agree. For contributions to this repo I think it is fair to ask for a bit more structure to the code, rather than just a working experiment.

**Comment by pjkohler** [comment]
Hi @steffejr, 

I have restructured the code to be a lot easier to read and modify. 

- Inversion of the images is now done in code. 
- I now store the stage of the experiment, image category, inversion, the correct answer and the participants answer. 
- I include Python code for converting the stimuli from their original names into names that are readable by JsPsych, based on an Excel file provided by the user. New users should be able to provide their own images and Excel files and use the experiment that way. 
- the user now has the option of randomizing the order of viewpoints shown (during learning phase of practice and part 1), and of randomizing the order of identities during those phases and of individual images during parts 2 and 3. The CFMT is usually run in the same order every time, so no randomization, and I will note this in the documentation. 

Some limitations remain: 

1. Non-standardized stimuli. This is just the way the test was created, and the way it has been run since.
2. Still not storing info about the particulars of each face, since this is challenging given the non-standard naming of the stimuli. 
3. For simplicity, I opted to use the same size for each image. This should not make a huge difference for the results. 

Let me know what you think. 

/Peter

**Comment by steffejr** [comment]
Hello Peter,
I just tested this without the cars and the faces. Everything worked well as far as I could tell. There is one type-o: Line #37 of the cfmt_setup _EN.js.
The word "face" is hard-coded.
In the results file, I see that the response is recorded as well as the correct response. Can you go one step further and assess whether each trial is correct? I don't know how this experiment assesses the results, but can you code the stimulus that was presented, its orientation, and its noise level? Are you interested in if there are perseverative errors where the user thinks they saw one face consistently, but they did not? Just wondering. I like to get as much as possible into my results files to make my analysis step a bit easier.

Good job.
IHTH,
J

**Comment by pjkohler** [comment]
- Good catch with the hard-coded "face". 
- Of course I though about assessing whether each trial was correct, but I got lazy. Thanks for pushing me, I have added that now. 
- if you mean orientation in the sense of was it inverted or not, that should already be stored. I'll double-check. 
- the stimulus presented is already stored in "stimulus" 
- noise-level, hm, yeah it is a pretty unclear from the current set of stimuli (which are standardized sets, shown in the same order every time, according to the standards of the CFMT). I think I will leave that as something users can add later as needed. 
- it should be possible to assess perseverative errors from the current data. 

I will test on more time, and then merge.

**Comment by pjkohler** [comment]
Testing done. Merging.

**Pull request merged**
