### PR TITLE
Ebbinghaus Experiment

### PR DESCRIPTION
**Pull request by pjkohler**
Pull request for my version of the Ebbinghaus Experiment. Pretty simple, should be pretty much ready to go. Put happy to hear about what I may have overlooked.

### CODE REVIEW

**Comment by pjkohler** [comment]
@jodeleeuw: Could you review this at some point?

**Comment by steffejr** [comment]
I tested this and it works great. Here are a few comments.

The instructions after every trial is super distracting. Can you put the instructions before each block? Otherwise it is a lot of flashing on the screen. Or you can keep the instructions on the screen continuously?

If we are going to use setup files with specific languages, then all text that the participant sees should be included in the setup file and called as variables in the experiment. This makes it easier to modify and for us to provide experiments in multiple languages where only the setup file changes. 

The code looks very neat and clean and the readme and setup files look great.

Nice job

**Comment by pjkohler** [comment]
good suggestions - will address them shortly. 

/Peter

**Comment by pjkohler** [comment]
Alright, I think I addressed your concerns. The issue with the messages to participants is that they utilize variables that are declared when the code is run. I found a workaround using string replacement, but I would be interested if anyone knows of a cleaner way to do it. Take a look.

**Comment by steffejr** [comment]
There is a problem with the ebbinghaus_setup_EN.js file on line #22 in the <p color>. I don't know what the problem is though.
Other than that it looks good.

**Comment by pjkohler** [comment]
weird, I don't know how I was ever able to run with that code. I added the text color change (to white) to set css file, which is probably better anyway. Merging.

**Pull request merged**
